### PR TITLE
refactor: migrate to qwik 1.x

### PR DESCRIPTION
**Pull request by elianiva**

### CODE REVIEW

**Comment by aldy505** [comment]
eslint errors:

```
/__w/hacktoberfest/hacktoberfest/frontend/src/env.d.ts
  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/src/env.d.ts` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
```

**Review by aldy505 — APPROVED** [review]
Everything looks good, yet the ESLint still throwing some issues.

**Review by krowter — APPROVED** [review]
Approved for the MR, but I can't resolve the eslint warning either using steps outlined in https://stackoverflow.com/a/64283139

**Comment by aldy505** [comment]
@elianiva Can you skip the eslint check on CI to have `continue-on-error` set to true? https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

The Docker image won't be built if the CI failed.

**Pull request merged**
